language: python
python:
  - "3.5"
install:
  - pip install .
  - pip install -r requirements.txt
script:
  - "nosetests httpobs/tests -e scored_test --with-coverage --cover-package=httpobs"
  - "flake8 --config .flake8 httpobs"
